"""add comment summary column

Revision ID: adc9bc876117
Revises: f33780c00af5
Create Date: 2025-03-01 10:27:40.433116

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "adc9bc876117"
down_revision: Union[str, None] = "f33780c00af5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("comments", sa.Column("summary", sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("comments", "summary")
    # ### end Alembic commands ###
