"""comment characteristic column

Revision ID: f33780c00af5
Revises: 950edbb408a3
Create Date: 2025-02-24 15:54:37.501103

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f33780c00af5"
down_revision: Union[str, None] = "950edbb408a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("comments", sa.Column("characteristic", sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("comments", "characteristic")
    # ### end Alembic commands ###
