name: Collector workflow
on:
  push:
    paths:
      - 'collector/**'
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        working-directory: ./collector
        run: |
          pip install poetry;
          poetry install;
      - name: Run test
        working-directory: ./collector
        run: |
          poetry run pytest;

  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        working-directory: ./collector
        run: |
          pip install poetry;
          poetry install;
      - name: Run lint check
        working-directory: ./collector
        run: |
          poetry run black --check .;

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        working-directory: ./collector
        run: |
          pip install poetry;
          poetry install;
      - name: Run lint check
        working-directory: ./collector
        run: |
          poetry run ruff check .;


  collect:
    needs: [test, format, lint]
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: 'actions/checkout@v4'
      - uses: 'google-github-actions/auth@v2'
        id: 'auth'
        with:
          project_id: 'evident-trees-449214-s9'
          workload_identity_provider: 'projects/369525575533/locations/global/workloadIdentityPools/cs3203-team-1/providers/github'
          service_account: 'cs3203-github-actions@evident-trees-449214-s9.iam.gserviceaccount.com'
          token_format: 'access_token'
      - name: Set up python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        working-directory: ./collector
        run: |
          pip install poetry;
          poetry install;
      - name: Collect reddit posts
        env:
          CLIENT_ID: ${{ secrets.CI_REDDIT_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CI_REDDIT_CLIENT_SECRET }}
        run: |
          poetry run start
      - name: Upload artifact to S3
        working-directory: ./collector
        run: |
          gcloud storage cp *.json gs://cs3203-bucket-1/extractor/
