name: Test and Upload Coverage

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [collector, extractor, loader, server, transformer, travelwise-common]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies for ${{ matrix.module }}
        run: |
          cd ${{ matrix.module }}
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run tests with coverage for ${{ matrix.module }}
        run: |
          cd ${{ matrix.module }}
          poetry run pytest --cov=src --cov-report=xml --cov-report=html

      - name: Upload coverage report for ${{ matrix.module }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.module }}
          path: ${{ matrix.module }}/coverage.xml
          retention-days: 7

  merge-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download coverage reports
        uses: actions/download-artifact@v4
        with:
          path: coverage_reports

      - name: Install coverage package
        run: |
          pip install coverage

      - name: Merge coverage reports
        run: |
          # Create a directory to store the merged coverage
          mkdir -p merged_coverage
          
          # Combine all coverage XML files into one
          coverage combine coverage_reports/coverage-*/coverage.xml  # Combining the downloaded files
          
          # Generate the HTML report from the merged coverage data
          coverage html -d merged_coverage

      - name: Upload merged coverage report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: merged-coverage
          path: merged_coverage
          retention-days: 7

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: merged_coverage

      - name: Deploy
        uses: actions/deploy-pages@v4
