name: extractor workflow
on:
  push:
    paths:
      - 'extractor/**'
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        working-directory: ./extractor
        run: |
          pip install poetry;
          poetry install;
      - name: Run test
        working-directory: ./extractor
        run: |
          poetry run pytest;

  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        working-directory: ./extractor
        run: |
          pip install poetry;
          poetry install;
      - name: Run lint check
        working-directory: ./extractor
        run: |
          poetry run black --check .;

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        working-directory: ./extractor
        run: |
          pip install poetry;
          poetry install;
      - name: Run lint check
        working-directory: ./extractor
        run: |
          poetry run ruff check .;

