name: travelwise common workflow

on:
  push:
    paths:
      - 'travelwise-common/**'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        working-directory: ./travelwise-common
        run: |
          pip install poetry
          poetry install
      - name: Run test
        working-directory: ./travelwise-common
        run: |
          poetry run pytest

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        working-directory: ./travelwise-common
        run: |
          pip install poetry
          poetry install
      - name: Run lint check
        working-directory: ./travelwise-common
        run: |
          poetry run black --check .

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        working-directory: ./travelwise-common
        run: |
          pip install poetry
          poetry install
      - name: Run lint check
        working-directory: ./travelwise-common
        run: |
          poetry run ruff check .

  publish:
    needs: [test, format, lint]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Set up python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        working-directory: ./travelwise-common
        run: |
          pip install poetry
          poetry install
      - name: Check if pyproject.toml version changed
        id: version_check
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q "travelwise-common/pyproject.toml"; then
            if git diff HEAD^ HEAD -- "travelwise-common/pyproject.toml" | grep -q '^\+version'; then
              echo "version_changed=true" >> $GITHUB_ENV
            else
              echo "version_changed=false" >> $GITHUB_ENV
            fi
          else
            echo "version_changed=false" >> $GITHUB_ENV
          fi
      - name: Build package
        if: env.version_changed == 'true'
        working-directory: ./travelwise-common
        run: |
          poetry build
      - name: Publish to PyPI
        if: env.version_changed == 'true'
        working-directory: ./travelwise-common
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          poetry publish --username __token__ --password $POETRY_PYPI_TOKEN_PYPI
  update-dependencies:
    needs: [publish]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: pip install poetry

      - name: Find and update pyproject.toml dependencies
        run: |
          for project in $(find . -name "pyproject.toml" -not -path "./travelwise-common/*"); do
            dir=$(dirname "$project")
            echo "Updating travelwise-common in $dir"
            cd "$dir"
            poetry update travelwise-common
            cd -
          done

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "chore: update travelwise-common to latest version"
          git push
        continue-on-error: true
