name: Update travelwise-common Versions

on:
  workflow_dispatch:
  push:
    paths:
      - "travelwise-common/pyproject.toml"

jobs:
  update-versions:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        working-directory: ./travelwise-common
        run: |
          pip install poetry
          poetry install

      - name: Get latest travelwise-common version
        id: get_version
        working-directory: ./travelwise-common
        run: |
          VERSION=$(poetry version --short)
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Update travelwise-common versions in repo
        run: |
          find . -type f \( -name 'pyproject.toml' -o -name 'requirements.txt' -o -name '*.lock' \) -exec sed -i "s/travelwise-common = \".*\"/travelwise-common = \"${{ env.version }}\"/g" {} +

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b update-travelwise-common-${{ env.version }}
          git add .
          git commit -m "Update travelwise-common version to ${{ env.version }}"
          git push origin update-travelwise-common-${{ env.version }}

      - name: Create pull request
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const branch = `update-travelwise-common-${{ env.version }}`;
            const title = `Update travelwise-common to ${{ env.version }}`;
            const body = "This PR updates travelwise-common to the latest version.";
            github.rest.pulls.create({
              owner,
              repo,
              title,
              head: branch,
              base: "main",
              body
            });
